# Generated by Django 5.0.7 on 2024-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='document',
            field=models.FileField(blank=True, upload_to='project_document/'),
        ),
    ]
